用户指南
------------

这部分文档将会展示如何开始在 Flask 中使用 Flask-SQLAlchemy。

.. toctree::
   :maxdepth: 2

   quickstart
   contexts
   config
   models
   queries
   binds
   signals

API 参考
-------------

如果您在寻找一个特定函数、类或者方法的信息，那么这部分文档就是为您准备的。

.. toctree::
   :maxdepth: 2

   api

附加说明
----------------

关于这个项目的法律信息请参阅 Flask 的 license_。

.. toctree::
   :maxdepth: 2

   changelog

.. _license: http://flask.pocoo.org/docs/license/
