用户指南
------------

这部分文档将向你展示如何在 Flask 中使用 Flask-RESTful。

.. toctree::
   :maxdepth: 2

   installation
   quickstart
   reqparse 
   fields
   extending
   intermediate-usage

API 参考
-------------

如果你正在查询特定函数，类或者方法的信息，这部分文档就是为你准备的。

.. toctree::
   :maxdepth: 2

   api

其它注意事项
----------------

关于这个项目的法律信息请参阅 Flask 的 license_。

.. toctree::
   :maxdepth: 2

   testing

.. _license: http://flask.pocoo.org/docs/license/

